FROM node:16.15.0-alpine3.15
WORKDIR /app/server
RUN apk add bash
#instead of . you can do /app/client, but because the working directory is /app/clinet we will use . that means the working directory
COPY package-lock.json .
COPY package.json .

RUN npm install
COPY . .
